### ISSUE TITLE
Infinite Intersection

### ISSUE THREAD

**Issue by Oscar-Liang** [alecjacobson/computer-graphics-ray-casting#17]
For a plane/triangle, can we assume that there will be no ray that lies on it, meaning that there are infinitely many intersection points?

**Comment by ericpko** [comment]
You can check if your ray's direction is perpendicular to the normal vector of the plane. Then you can return _________

**Comment by Oscar-Liang** [comment]
That's fine for planes but doesn't work with triangles. The ray doesn't necessarily intersect with the triangle even if it lies in the same plane as it.

**Comment by shimismith** [comment]
I was wondering the same thing and I now I'm thinking, what would it look like if light that is parallel to a plane hit your eye (no matter if there is a triangle on this plane or not). I'm thinking you wouldn't see anything.

**Comment by abhimadan** [comment]
> For a plane/triangle, can we assume that there will be no ray that lies on it, meaning that there are infinitely many intersection points?

Don't assume that rays can never be parallel to planes and triangles. Think about this case: if you shoot a ray for a pixel in the middle of the image (so the ray is parallel to the xz plane), and you had a plane that's also parallel to the xz plane, would you be able to see the plane at that pixel? Also, planes and triangles are 2D shapes in a 3D space, so they have zero depth; how would it look if you tried to view the "side" of these shapes?

> That's fine for planes but doesn't work with triangles. The ray doesn't necessarily intersect with the triangle even if it lies in the same plane as it.

Good observation; even if the ray isn't parallel to the plane the triangle is on, it may still not intersect the triangle. You need to think of a way to check whether or not the ray goes through the triangle itself, rather than just the plane it's on.
